### PR TITLE
Upgraded cleanlab and package fixes 

### PR DESCRIPTION
**Pull request by duarteocarmo**
Awesome approach with the makefile - I'm sold!

Double check please - I'm running on M1 and `whatlies` gives me problems.

### CODE REVIEW

**Comment by duarteocarmo** [comment]
Should fix #43

**Comment by koaning** [comment]
Ah yeah, whatlies uses some tensorflow stuff that M1 doesn't enjoy working with. Thanks for the PR!

**Comment by koaning** [comment]
Related; I'm thinking about turning cleanlab into an optional dependency in the future. Have you found that it finds examples that the other tools don't?

**Comment by duarteocarmo** [comment]
So a couple of comments: 
- The cleanlabel method was not really working (is was giving me an error related to a `multilabel` parameter inside one of the cleanlab functions)
- The most important thing to visualize for me is the "top-k-worst" method. I.e. the examples where my model was wrong but gave a very high probability to the predicted class. I could not reproduce that with either this package, or the cleanlabel package.. 

So struggling even to get this: 
```python 
top_k_df[top_k_df.label_name != top_k_df.prediction].sort_values(by="prediction_probability", ascending=False).head(k)
```
I am not sure you'll get my point.. lmk

**Comment by duarteocarmo** [comment]
So to cut it short - yes - if it's not needed to run a lot of the functionality - make it optional. Cleanlab does a whole lot of things. This package does **one thing well**.

**Comment by koaning** [comment]
It's likely that for the 0.3.0 version, I'll make it optional. But I'd like to check if their new version also has some new features built in. Will see later ... 😄

**Pull request merged**
