### PR TITLE
Added a LICENSE

### PR DESCRIPTION
**Pull request by sugatoray**
Hi @koaning, 

I am assuming MIT License is okay for this repository. If you think otherwise, please feel free to make changes in the PR accordingly.

- [x] Added an MIT License
- [x] ~~Added a Citation file~~ _Removed the citation file and updated the name of the PR._
	  - ~~If you have an `orcid`, please consider adding it to the `citation.cff` file.~~

### CODE REVIEW

**Comment by koaning** [comment]
Oh yeah, I totally forgot the license, good call! 

I'd prefer not to add a citation file just yet.  I think a citation should be added once the project can claim some form of stability and the project isn't even a week old. I'll gladly merge the PR once the citation file is removed tho 👍

**Comment by sugatoray** [comment]
@koaning Makes sense. I am dropping the citation file from the PR then.

**Comment by sugatoray** [comment]
@koaning Also, the PyPI package does not have any License file with it. So, if you could kindly push another release with the License, that would be great. Thank you.

**Comment by sugatoray** [comment]
> _Removed the citation file and updated the name of the PR._

**Comment by koaning** [comment]
Just pushed!

**Pull request merged**
